version: '3.5'

services: 

    redis:
      image: redis

    db:
      image: postgres
      container_name: db
      restart: unless-stopped
      environment:
        - POSTGRES_PASSWORD=password
        - POSTGRES_USER=user
        - POSTGRES_DB=db 
      volumes:
        - database:/var/lib/postgresql/data

    back: 
      build: ./backend-example-docker
      ports: 
        - 8000:8000
      environment: 
        - FRONT_URL=http://localhost:5000
        - REDIS=redis
        - DB_USERNAME=user
        - DB_PASSWORD=password
        - DB_HOST=db 
        - DB_NAME=db
      volumes:
        - ./logs.txt:/mydir/logs.txt
      depends_on:
        - db
      container_name: back

    front:
      build: ./frontend-example-docker
      ports:
        - 5000:5000
      environment:
        - API_URL=http://localhost:8000
      container_name: front
      depends_on: 
        - back

volumes:
    database:
