version: '3.5'

services: 

    redis:
      image: redis

    db:
      image: postgres
      container_name: db
      environment:
        - POSTGRES_PASSWORD=password
        - POSTGRES_USER=user
        - POSTGRES_DB=db 

    back: 
      build: ./backend-example-docker
      environment: 
        - FRONT_URL=http://front:5000
        - REDIS=redis
        - DB_USERNAME=user
        - DB_PASSWORD=password
        - DB_HOST=db 
        - DB_NAME=db
      volumes:
        - ./logs.txt:/mydir/logs.txt
      depends_on:
        - db
      container_name: back

    front:
      build: ./frontend-example-docker
      environment:
        - API_URL=http://back:8000
      container_name: front
      depends_on: 
        - back

    nginx:
      image: nginx
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
      ports:
        - 80:80
